### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by shreefentsar**
adding confirmation of work on big sur

### CODE REVIEW

**Comment by budiselic** [comment]
I think little more testing is needed, for me is not working

**Comment by greendog99** [comment]
Working for me on Big Sur, 2019 16" Macbook Pro.

**Comment by R0LA1mRifcF8yAkk** [comment]
For me it seems to not work on Big Sur. Do I need to reset the SMC or something?

**Comment by R0LA1mRifcF8yAkk** [comment]
Update: working now. Not entirely sure what changed.

**Pull request closed without merging**
